import type { Metadata } from "next";
import { Geist, Geist_Mono , Poppins , Maitree } from "next/font/google";
import { Navbar } from "./components/home/Navbar";
import Footer from "./components/home/Footer";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: [ "600"],
  style: "normal",
  variable:"--font-poppins",
  subsets:["latin"],
  preload: true,

});

const maitree = Maitree({
  weight: ["400" ,"700"],
  style: "normal",
  variable: "--font-maitree",
  subsets: ["latin"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <Navbar />
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${maitree.variable} antialiased  `}
      >
        {children}
      </body>
    </html>
    <Footer />
    </>
  );
}
